api/urls.py
from django.urls import path
from . import views 

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getProject),
    path('projects/<str:pk>/vote/', views.projectVote),
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# django authentication system/ auth views, we're using for pw reset
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),

    # built-in class based views for pw reset see comments at bottom rendered w/ .as_view() method; naming has to match django documentation; django provides built-in templates; if want to customize must create own and enter template_name as attribute to view call:
    # link to pw reset page
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name="reset_password"),
    # confirmation that pw reset email sent
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'),
         name="password_reset_done"),
    # link in pw reset instructions email that was sent, <uidb64> encodes user id in base 64 encryption and token is passed in
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'),
         name="password_reset_confirm"),
    # pw reset success message
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'),
         name="password_reset_complete"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# 1 - User submits email for reset              //PasswordResetView.as_view()           //name="reset_password"
# 2 - Email sent message                        //PasswordResetDoneView.as_view()        //name="passsword_reset_done"
# 3 - Email with link and reset instructions    //PasswordResetConfirmView()            //name="password_reset_confirm"
# 4 - Password successfully reset message       //PasswordResetCompleteView.as_view()   //name="password_reset_complete"

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user-profile'),
    path('account/', views.userAccount, name='account'),
    path('edit-account/', views.editAccount, name='edit-account'),
    path('create-skill/', views.createSkill, name='create-skill'),
    path('update-skill/<str:pk>/', views.updateSkill, name='update-skill'),
    path('delete-skill/<str:pk>/', views.deleteSkill, name='delete-skill'),
    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='message'),
    path('create-message/<str:pk>/', views.createMessage, name='create-message'),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default='default.jpg')
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

    class Meta:
        # orders projects, checks for highest rated first then most total votes, then title if there are ties
        ordering = ['-vote_ratio', '-vote_total', 'title']

    # get all reviewers for a project to check for no repeats
    @property
    def reviewers(self):
        # values_list(*fields, flat=False, named=False) This is similar to values() except that instead of returning dictionaries, it returns tuples when iterated over. Each tuple contains the value from the respective field or expression passed into the values_list() call — checks by parent class id 'owner__id', flat=true converts from object to true list
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    # so can run as an attribute instead of a method, allows method to accessed like a regular property, e.g. project.getVoteCount
    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        # update values in fields of the instance
        self.vote_total = totalVotes
        self.vote_ratio = ratio
        self.save()



class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        # makes sure each person can only leave one review per project
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.project.title

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User #built in user class related to profile class
import uuid


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    headline = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_twitter = models.CharField(max_length=200, null=True, blank=True)
    social_linkedin = models.CharField(max_length=200, null=True, blank=True)
    social_stackoverflow = models.CharField(max_length=200, null=True, blank=True)
    social_website = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)

    class Meta:
        # orders profiles alphabetically by name
        ordering = ['name']

class Skill(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

class Message(models.Model):
    # on_delete set to null so a record of messages sent remains even if sender deletes acct,
    # null set to true b/c so sender does not need to have an acct, so form can be submitted w/o
    # official profile relationship
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    # related name allows to use messages instead of message_set since there are two foreign keys to distinguish between them
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='messages')
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    # indicate whether or not recipient has read message
    is_read = models.BooleanField(default=False, null=True)
    # blank default is false, so a message body must be created 
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.subject)

    class Meta:
        # set ordering of messages so that unread and then most recent appear at the top
        # goes in order of index in list
        ordering = ['is_read', '-created']

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm # built in Django form, takes care of pw hashing
from django.contrib.auth.models import User # for authentication
from .models import Profile, Skill, Message

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',
            }
    # styles fields
    def __init__(self, *args, **kwargs):
        # override super
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        # apply class 'input' to each field
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username', 'location', 'bio', 'headline', 'profile_image', 'social_github', 'social_linkedin', 'social_twitter', 'social_stackoverflow', 'social_website' ]

        # styles fields
    def __init__(self, *args, **kwargs):
        # override super
        super(ProfileForm, self).__init__(*args, **kwargs)
        # apply class 'input' to each field
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        # lists all fields from Skill model on form
        fields = '__all__'
        # excludes owner field which we don't want on form
        exclude = ['owner']
        # styles fields
    def __init__(self, *args, **kwargs):
        # override super
        super(SkillForm, self).__init__(*args, **kwargs)
        # apply class 'input' to each field
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        # override super
        super(MessageForm, self).__init__(*args, **kwargs)
        # apply class 'input' to each field
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}

  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}" target="_blank"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.headline}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if profile.social_stackoverflow %}
                <li>
                  <a title="Stackoverflow" href="{{profile.social_stackoverflow}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                {% endif %}
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}"" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}"" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}"" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in skills %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>{{skill.description}}</p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <!--when link is clicked, extra value ?next=/account is appended making it dynamic-->
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in projects %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'project' project.id %}"><img src="{{project.featured_image.url}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'project' project.id %}">{{project.title}}</a>
                <p>{{project.description|truncatechars:150}}</p><!-- used truncate instead of slice-->>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <!--when link is clicked, extra value ?next=/account is appended making it dynamic-->
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}            
           </table>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
    <ul class="messages">
      {% for message in messageRequests %}
      {% if message.is_read == False %}
      <li class="message message--unread">
      {% else %}      
      <li class="message">
      {% endif %}
        <a href="{% url 'message' message.id %}" target="_blank">
          <span class="message__author">{{message.name}}</span>
          <span class="message__subject">{{message.subject}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</main>

{% endblock %}

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

{% if page == 'register' %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Register an Account</h3>
      <p>Create a new developer account</p>
    </div>

    <form method='POST' action="{% url 'register' %}" class="form auth__form">      
      {% csrf_token %}
      {% for field in form %}
      <div class="form__field">
        <label for="formInput#text">{{field.label}} </label>
        {{field}}
        <!--display error message for invalid entry using 
          help_text built in messages about required input-->
        {% comment %} {% if field.help_text %}
          <small>{{field.help_text}}</small>
        {% endif %} {% endcomment %}
        <!--built in field error message-->
        {% for error in field.errors %}
          <p style="color:red">{{error}}</p>
        {% endfor %}
      </div>
      {% endfor %}
      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
      </div>
    </form>
    <div class="auth__alternative">
      <p>Already have an Account?</p>
      <a href="{% url 'login' %}">Log In</a>
    </div>
  </div>
</div>
{% else %}
<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>
      <!--leave action blank, so an pass in orginal GET request even when submitting a POST request, request still gets sent to login page; also added class="form auth__form" but I may have deleted that before so it may need deleted again if so -->
      <form action="" method="POST" class="form auth__form">
        {% csrf_token %}
        <!-- Input:Username -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="{% url 'reset_password' %}">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'register' %}">Sign Up</a>
      </div>
    </div>
  </div>
{% endif %}

{% endblock content %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
      <h2 class="message__subject">{{message.subject}}</h2>
        <a href="profile.html" class="message__author">{{message.name}}</a>
        <p class="message__date">{{message.created}}</p>
        <!-- |linebreaksbr ensures line breaks in message are added in template-->
        <div class="message__body">{{message.body|linebreaksbr}}</div>
    </div>
  </div>
</main>

{% endblock %}

users/templates/users/message_form.html
{% extends 'main.html' %}
{% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-profile' recipient.id %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                <!--if message sender is not authenticated add fields for name and email, already have this info if they are authenticated-->
                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                    <label for="formInput#text">{{form.name.label}}</label>
                    {{form.name}}           
                </div>
                <div class="form__field">
                    <label for="formInput#text">{{form.email.label}}</label>
                    {{form.email}}           
                </div>
                {% endif %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{form.subject.label}}</label>
                    {{form.subject}}               
                </div>
                <div class="form__field">
                    <label for="formInput#text">{{form.body.label}}</label>
                    {{form.body}}               
                </div>

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/profile_form.html
{% extends 'main.html'%}

{% block content %}

 <!-- Main Section -->
 <main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>
            <!--enctype is for image files-->
            <form class="form" method="POST" action="{% url 'edit-account' %}" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>

                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

 <!-- Main Section -->
 <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <!--send get request to backend -->
          <form id='searchForm' class="form" action="{% url 'profiles' %}" method="GET">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <!--name value is what GET method uses, name sent to backend-->
              <input class="input input--text" id="formInput#search" type="text" name="search_query" value="{{search_query}}"
                placeholder="Search by developer name, headline, or skill" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
        {% for profile in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.headline|truncatechars:50}}</h5><!--used truncate instead of slice--> 
                  </div>
                </div>
                <p class="dev__info">{{profile.bio|truncatechars:150}}</p> <!--used truncate instead of slice--> 
                <div class="dev__skills">
                {% for skill in profile.skill_set.all|slice:"6" %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                {% endfor %}
                </div>
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
    </section>

    <!--pass in profiles & custom_range from profiles view to pagination page-->
    {% include 'pagination.html' with queryset=profiles custom_range=custom_range %}
  </main>
{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.headline}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if profile.social_stackoverflow %}
                <li>
                  <a title="Stackoverflow" href="{{profile.social_stackoverflow}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                {% endif %}
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}"" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}"" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}"" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <!--only show button for devs other than signed in user so no one 
              can send themself a message; check if logged in user id matches id 
              of profile being viewed -->
              {% if request.user.profile.id != profile.id %}
              <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in topSkills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">{{skill.description}}</p>
              </div>
              {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill}}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
              {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:'s'}})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all%}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}